cms/urls.py
from django.conf.urls import url
from views import controller

urlpatterns = [
    url(r'^$', controller),
   
]

dazhu/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from views import get_404
admin.autodiscover()

handler404 = 'dazhu.views.get_404'

urlpatterns = [
    url(r'^$', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
    url(r'^ueditor/', include('ueditor.urls')),
   # url(r'^chat/', include('chat.urls')),
    url(r'^album/', include('album.urls')),
    url(r'^diary/', include('diary.urls')),
    url(r'^search', include('search.urls')),
    url(r'^message/', include('message.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^memo/', include('memo.urls')),
    url(r'^pan/', include('pan.urls')),
    url(r'^msg/', include('msg.urls')),
    url(r'^static/', include('handler_statics.urls')),
    url(r'^(.*)/(.*)/', include('cms.urls')),

]

memo/urls.py
from django.conf.urls import url
from views import create,list,edit

urlpatterns = [
    #url(r'^$', index.as_view()),
    url(r'create/$', create),
    url(r'list/$', list),
    url(r'^edit/(.+)/$',edit),
]

memo/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from account.models import Account
# Create your models here.
class Memo(models.Model):
    title = models.CharField(max_length=30)
    author = models.ForeignKey(Account)
    body = models.TextField()
    timestamp = models.DateTimeField(default = timezone.now)

dazhu/views.py
# coding:utf-8
'''
Created on Mar 21, 2016

@author: yzh
'''
from django.http import HttpResponse

def get_404(request):
    return HttpResponse(request.get_full_path() + u"神马也没找到")

memo/views.py
# coding:utf-8
from django.shortcuts import render

import django.utils.timezone
# Create your views here.
from django.views.generic import CreateView
from .models import Memo
from django import forms
from django.http import HttpResponseRedirect,HttpResponseForbidden
import datetime
from django.utils import timezone


class MemoForm(forms.Form):
    mid = forms.CharField(widget=forms.HiddenInput(), required=False)
    title = forms.CharField(label=u'标题', error_messages= \
        {'required': u'标题不能为空'}, required=True)

    body = forms.CharField(label=u'内容', error_messages= \
        {'required': u'内容不能为空'}, widget=forms.Textarea( \
        attrs={'rows': 10, 'cols': 40}))

    timestamp = forms.DateTimeField(label=u"时间", error_messages= \
        {'required': u'时间不能为空', 'invalid': u'请输入正确的时间'}, \
        initial=django.utils.timezone.now(),\
        input_formats=["%Y/%m/%d %H:%M:%S"], widget=\
        forms.DateTimeInput(attrs={'placeholder': '时间'}, format="%Y/%m/%d %H:%M:%S"))


def create(request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():  # 所有验证都通过
            temp_memo = Memo()
            temp_memo.title = form.cleaned_data['title']
            temp_memo.body = form.cleaned_data['body']
            temp_memo.body.replace("\r\n", "\n").replace("\n", "<br>")
            temp_memo.timestamp = form.cleaned_data['timestamp']
            temp_memo.author = request.user
            temp_memo.save()
            return HttpResponseRedirect("/memo/list/")
    else:
        form = MemoForm(initial={'timestamp': \
                                     django.utils.timezone.now()})
    return render(request, 'memo/memo_form.html', {'form': form})


def edit(request, mid):
    temp_memo = Memo.objects.get(id=int(mid))
    if temp_memo.author != request.user:
        return HttpResponseForbidden()
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():  # 所有验证都通过
            temp_memo.title = form.cleaned_data['title']
            temp_memo.body = form.cleaned_data['body']
            temp_memo.body.replace("\r\n", "\n").replace("\n", "<br>")
            temp_memo.timestamp = form.cleaned_data['timestamp']
            temp_memo.author = request.user
            temp_memo.save()
            return HttpResponseRedirect('/memo/list/')
    else:
        form = MemoForm(initial={'body': temp_memo.body.replace("<br>", "\r\n"), \
                                 'timestamp': temp_memo.timestamp, \
                                 "mid": temp_memo.id, \
                                 "title": temp_memo.title})
    return render(request, 'memo/memo_form.html', {'form': form})


def list(request):
    memoes = request.user.memo_set.all()
    return render(request, 'memo/list.html', {'memoes': memoes})

dazhu/templates/memo/list.html
{% extends "base.html" %}
<div></div>
{% block head %}
<script type="text/javascript">
    $(function(){

    });
</script>
{% endblock %}
{% block content %}
<section id="content">
    <div class="wrap-content">
        <div class="row block">
            <div id="main-content" class="col-2-3">
               <div class="wrap-col">
				   <section>
                        <a href="/memo/create/">创建新的</a>
                        {% for memo in memoes %}
                        <h3>
                            <span style="display:inline-block;min-width:72%;">
                                <a href="/memo/edit/{{memo.id}}/">
                                    {{memo.title|lower}}
                                </a>
                            </span>
                            <span style="color:silver;font-size:14px;
                                  padding-left:5px;font-style:italic;">
                                    {{memo.timestamp|date:"Y-m-d H:i"}}
                            </span>
                        </h3>
                        {% endfor %}
                   </section>
				</div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

dazhu/templates/memo/memo_form.html
{% extends "base.html" %}
<div></div>
{% block head %}
<script type="text/javascript"
			src="/static/js/sjcl.js"></script>
<script type="text/javascript">
    $(function(){
        $("#ecp").click(function(e){
            data = $("#id_body").val();
            edata = sjcl.encrypt($("#id_pwd").val(), data);
            $("#id_body").val(edata);
        });

        $("#dcp").click(function(e){
            data = $("#id_body").val();
            ddata = sjcl.decrypt($("#id_pwd").val(), data);
            $("#id_body").val(ddata);
        });
    });
</script>

<style>
    #contact-form input#id_timestamp {
        width:100%;
        margin-bottom:5px;
    }

    #contact-form textarea#id_body {
        font-size:14pt;
        width:100%;
        margin-bottom:5px;color:black;
    }
</style>
{% endblock %}
{% block content %}
<section id="content">
    <div class="wrap-content">
        <div class="row block">
            <div id="main-content" class="col-2-3">
               <div class="wrap-col">
				   <section>
						<form action="" id="contact-form" method="post">
                            {% csrf_token %}
                            {{ form.mid }}
                            <fieldset>
                                <div>
                                    <input id="id_title" style='width:100%;margin-bottom:5px;' placeholder="标题"
                                        name="title" type="text"
                                           value="{{form.title.value|default_if_none:''}}" />
                                    {{ form.title.errors }}
                                </div>
                                <div class="content">
                                    {{form.body}}
                                    {{ form.body.errors }}

                                    {{form.timestamp}}
                                    {{ form.timestamp.errors }}

                                    <input id="id_pwd" style="width:40%;margin-bottom:5px;" placeholder="密码" name="pwd"
                                           type="text" autocomplete="off" value="" />
                                    <input id="ecp" style="width:20%;" type="button" value="加密"/>
                                    <input id="dcp" style="width:20%;" type="button" value="解密"/>
                                </div>
                                <div>
                                    <input style="width:30%;" type="submit" value='创建/保存' />
                                </div>

                            </fieldset>
                        </form>
					</section>
				</div>
            </div>
        </div>
    </div>
</section>
{% endblock %}